name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install numpy separately
      run: pip install numpy==1.24.4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[gdrive]

    - name: Setup creds.json
      run: echo '${{ secrets.CREDS }}' > creds.json

    - name: Set GOOGLE_APPLICATION_CREDENTIALS env var
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/creds.json" >> $GITHUB_ENV

    - name: DVC Pull model from Google Drive
      run: dvc pull

    - name: Run unit tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest tests/ --verbose

    - name: Build Docker image
      run: docker build -t my-ml-api-app .
