name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r final_task/requirements.txt

    - name: Run unit tests
      run: |
        pytest final_task/tests/ --verbose

    - name: Build Docker image
      run: |
        docker build -t my-app -f final_task/Dockerfile .

    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 my-app
        sleep 5
        curl --fail http://localhost:8000/docs